package citi.hibernate.entity;
// Generated Aug 24, 2017 9:35:40 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private String ordersid;
	private Staff staff;
	private Stationery stationery;
	private Integer quantity;
	private Date update;

	public Orders() {
	}

	public Orders(String ordersid, Staff staff, Stationery stationery) {
		this.ordersid = ordersid;
		this.staff = staff;
		this.stationery = stationery;
	}

	public Orders(String ordersid, Staff staff, Stationery stationery, Integer quantity, Date update) {
		this.ordersid = ordersid;
		this.staff = staff;
		this.stationery = stationery;
		this.quantity = quantity;
		this.update = update;
	}

	public String getOrdersid() {
		return this.ordersid;
	}

	public void setOrdersid(String ordersid) {
		this.ordersid = ordersid;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Stationery getStationery() {
		return this.stationery;
	}

	public void setStationery(Stationery stationery) {
		this.stationery = stationery;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Date getUpdate() {
		return this.update;
	}

	public void setUpdate(Date update) {
		this.update = update;
	}

}
