package citi.hibernate.entity;
// Generated Aug 24, 2017 9:35:40 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Stationery generated by hbm2java
 */
public class Stationery implements java.io.Serializable {

	private int stationeryid;
	private String kind;
	private String name;
	private String standard;
	private BigDecimal price;
	@JsonIgnore
	private Set orderses = new HashSet(0);

	public Stationery() {
	}

	public Stationery(int stationeryid) {
		this.stationeryid = stationeryid;
	}

	public Stationery(int stationeryid, String kind, String name, String standard, BigDecimal price, Set orderses) {
		this.stationeryid = stationeryid;
		this.kind = kind;
		this.name = name;
		this.standard = standard;
		this.price = price;
		this.orderses = orderses;
	}
	public Stationery(int stationeryid, String kind, String name, String standard, BigDecimal price) {
		this.stationeryid = stationeryid;
		this.kind = kind;
		this.name = name;
		this.standard = standard;
		this.price = price;
	}
	public int getStationeryid() {
		return this.stationeryid;
	}

	public void setStationeryid(int stationeryid) {
		this.stationeryid = stationeryid;
	}

	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStandard() {
		return this.standard;
	}

	public void setStandard(String standard) {
		this.standard = standard;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	@JsonIgnore
	public Set getOrderses() {
		return this.orderses;
	}
	@JsonIgnore
	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
