package citi.hibernate.entity;
// Generated Aug 24, 2017 9:35:40 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Systeminfo generated by hbm2java
 */
public class Systeminfo implements java.io.Serializable {

	private int systemid;
	private String note;
	private Date startdate;
	private Date deadline;
	private Date update;
	private String operator;

	public Systeminfo() {
	}

	public Systeminfo(int systemid) {
		this.systemid = systemid;
	}

	public Systeminfo(int systemid, String note, Date startdate, Date deadline, Date update, String operator) {
		this.systemid = systemid;
		this.note = note;
		this.startdate = startdate;
		this.deadline = deadline;
		this.update = update;
		this.operator = operator;
	}
	public Systeminfo(String note, Date startdate, Date deadline, Date update, String operator) {
		this.note = note;
		this.startdate = startdate;
		this.deadline = deadline;
		this.update = update;
		this.operator = operator;
	}
	public int getSystemid() {
		return this.systemid;
	}

	public void setSystemid(int systemid) {
		this.systemid = systemid;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	public Date getUpdate() {
		return this.update;
	}

	public void setUpdate(Date update) {
		this.update = update;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

}
